module.exports = {
  extends: [
    // add more generic rulesets here, such as:
    // 'eslint:recommended',
    'plugin:toml/standard'
  ],
  rules: {
    // override/add rules settings here, such as:
    // 'toml/rule-name': 'error'
   "comma-spacing": "error",
   "no-multi-spaces": ["error", { "exceptions": { "TOMLKeyValue": true } }],
   "no-multiple-empty-lines": "error",
   "no-trailing-spaces": "error"
  }
}
